# Generated by Django 6.0.5 on 2026-05-18 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('whatsapp_number', models.CharField(help_text="Format: 2348012345678 (No '+' or spaces)", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., 2-Bedroom Apartment in Ekosodin', max_length=200)),
                ('description', models.TextField(help_text='Details about water, electricity, security, etc.')),
                ('price', models.CharField(help_text='e.g., ₦150,000 / year', max_length=100)),
                ('location', models.CharField(help_text='e.g., BDPA, Ugbowo', max_length=200)),
                ('video', models.FileField(upload_to='house_videos/')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='housing.agent')),
            ],
        ),
    ]
