# Generated by Django 6.0.5 on 2026-06-26 19:58

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0002_alter_house_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='house',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='house',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='house',
            name='video',
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('video', cloudinary.models.CloudinaryField(max_length=255, verbose_name='video')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='housing.agent')),
            ],
        ),
    ]
