# Generated by Django 6.0.5 on 2026-06-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0003_remove_house_agent_remove_house_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
