# Generated by Django 6.0.5 on 2026-06-26 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0004_house_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 6, 26, 23, 7, 12, 927376, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
