# Generated by Django 6.0.5 on 2026-06-26 23:15

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0005_house_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='video',
        ),
        migrations.AddField(
            model_name='house',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='housing.agent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='video',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='video'),
            preserve_default=False,
        ),
    ]
