# Generated by Django 6.0.5 on 2026-09-26 21:44

import cloudinary.models
import housing.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0006_remove_subscriber_agent_remove_subscriber_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='video',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[housing.models.validate_video_size], verbose_name='video'),
        ),
    ]
